### ISSUE TITLE
Hi, I have a question. If "x.shape[1] == L+self.num_mem_token", then it seems that the i in "mode: x[:, i, :]" does not correspond to the position of mode, because the first position is mem _token.

### ISSUE THREAD

**Issue by SmallXieGithub** [sangminwoo/ActionMAE#4]
https://github.com/sangminwoo/ActionMAE/blob/4ae5a813ebf0ea9f4ba3655d6cefb215642309c4/lib/modeling/actionmae.py#L365

**Comment by SmallXieGithub** [comment]
Hello?

**Comment by sangminwoo** [comment]
Can you elaborate on your question a bit more?

**Comment by SmallXieGithub** [comment]
Should the code  (else: x = x[:, self.num_mem_token:, :])be added here(https://github.com/sangminwoo/ActionMAE/blob/4ae5a813ebf0ea9f4ba3655d6cefb215642309c4/lib/modeling/actionmae.py#LL363C1-L363C1)?

**Comment by sangminwoo** [comment]
In L359, if "x.shape[1] != L+self.num_mem_token" is False, in which line did you see the error?

**Comment by SmallXieGithub** [comment]
In L359, if "x.shape[1] ! = L+self.num_mem_token" is false, then L226 will not be executed and the cls token will be preserved, resulting in errors in L365-368 (the indexes seem to be out of correspondence).

**Comment by SmallXieGithub** [comment]
Hi?

**Comment by sangminwoo** [comment]
Sorry for the late reply.
I acknowledge your point. Please try the fix, and report back if you see any further errors.
Many thanks.

**Comment by SmallXieGithub** [comment]
Thank you very much for your answer.
